---
title: "Data Visualization"
output:
  html_document: default
  pdf_document: default
date: "2024-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
setwd("/Users/nithyashree/Documents/Data Visualization")
#read the data
crime420co4 <- read.csv("crime23.csv")
temp180co4  <- read.csv("temp2023.csv")
```


```{r}
head(crime420co4)
head(temp180co4)

```
```{r}

library(stringr)
library(lubridate)
library(wordcloud2)
library(DT)
library(dplyr)
library(plotly)
library(ggplot2)
library(viridis)
library(MASS)
library(leaflet)
```

```{r}

# View the structure of the data frames
str(crime420co4)
str(temp180co4)

# Check for missing values
sum(is.na(crime420co4))
sum(is.na(temp180co4))


```
```{r}

# Create a new variable for the cleaned dataset
cleaned_crimeco4 <- crime420co4

#Get list of numeric columns
num_co4_col <- sapply(cleaned_crimeco4, is.numeric)

# Replace NA values in numeric columns with mean
cleaned_crimeco4[num_co4_col] <- lapply(cleaned_crimeco4[num_co4_col], function(x) {
    ifelse(is.na(x), round(mean(x, na.rm = TRUE), 1), x)
})

# Data cleaning for cleaned_crimeco4
# Fill missing values in outcome_status
cleaned_crimeco4$outcome_status[is.na(cleaned_crimeco4$outcome_status)] <- "No Information"

# Clean street names in crime data
cleaned_crimeco4$street_name <- str_trim(str_to_lower(cleaned_crimeco4$street_name))

# Parse the date column in the cleaned_crimeco4 dataset
cleaned_crimeco4$date <- ym(cleaned_crimeco4$date)

# Remove irrelevant columns (context, location_subtype)
cleaned_crimeco4 <- subset(cleaned_crimeco4, select = -c(context, location_subtype))

head(cleaned_crimeco4)


```



```{r}

#cleaned dataset name
cleaned_tempco4 <- temp180co4

# List of numeric columns in temp180co4
num_col_tempco4 <- sapply(cleaned_tempco4, is.numeric)

# Replace NA values in numeric columns with mean, preserving original precision
cleaned_tempco4[num_col_tempco4] <- lapply(cleaned_tempco4[num_col_tempco4], function(x) {
  ifelse(is.na(x), round(mean(x, na.rm = TRUE), 1), x)  
})



# Parse the Date column in temp180co4 dataset
cleaned_tempco4$Date <- ymd(cleaned_tempco4$Date)

# Remove irrelevant columns (PreselevHp, SnowDepcm)
cleaned_tempco4 <- cleaned_tempco4[, !names(cleaned_tempco4) %in% c("PreselevHp", "SnowDepcm")]

head(cleaned_tempco4)


```

```{r}
# View the structure of the data frames
str(cleaned_tempco4)
str(cleaned_crimeco4)
# Check for missing values
sum(is.na(cleaned_tempco4))
sum(is.na(cleaned_crimeco4))

```
Lets perform various analyses to gain information and potentially improve the safety and well-being of the community.
```{r}
# Create a table of crime categories and their frequencies
crime_catco4_freq <- table(cleaned_crimeco4$category)

# Convert the table to a data frame
crime_catco4_df <- as.data.frame(crime_catco4_freq)

# Rename the columns for better visualization
colnames(crime_catco4_df) <- c("Crime_Category", "Frequency")

# Generate the word cloud
wordcloud2(crime_catco4_df, size = 1.2)
```

```{r}


# Calculate percentages for the frequency table
cat_table_percco4 <- prop.table(crime_catco4_freq) * 100

# Convert the table to a data frame and include percentages
#cat_table_dfco4 <- as.data.frame.table(crime_catco4_freq)
crime_catco4_df$Percentage <- paste0(round(cat_table_percco4, 2), "%")

# Create a two-way table for 'category' and 'street_name'
tw_co4 <- table(cleaned_crimeco4$category, cleaned_crimeco4$street_name)

# Calculate percentages for the two-way table
tw_streetco4_per <- prop.table(tw_co4, margin = 1) * 100

# Convert tables to data frames and include percentages
tw_df <- as.data.frame(tw_co4)
tw_df$Percentage <- paste0(round(tw_streetco4_per, 2), "%")

# Create interactive tables
datatable(crime_catco4_df, caption = "Frequency Table for Category")
datatable(tw_df, caption = "Two-way Table for Category and Street Name")



```

```{r}

# Create an interactive bar plot for crime category in the crime dataset
barpt_co4 <- plot_ly(data = crime_catco4_df, y = ~Crime_Category, x = ~Frequency, type = 'bar', 
                     orientation = 'h',
                     name = "Category Frequency",
                     marker = list(color = "maroon")) %>%
             layout(title = "Crime Category Frequency",
                    yaxis = list(title = "Category"),
                    xaxis = list(title = "Frequency"))

# Display the interactive plot
barpt_co4


```




```{r}

# Filter dataset to retrieve only violent crime incidents
vc_co4 <- cleaned_crimeco4 %>%
  filter(category == "violent-crime")

# Count occurrences of violent crime incidents for each street
strt_cunts <- vc_co4 %>%
  count(street_name) %>%
  arrange(desc(n))  

# Select the top 10 streets
top_10_strts <- strt_cunts %>%
  slice_max(n, n = 10)

# Define a qualitative color palette from Color Brewer
color_palette <- c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00", "#ffff33", "#a65628", "#f781bf", "#999999")

# Create a pie chart for the top 10 streets with custom colors 
pie_chrt_co4 <- plot_ly(top_10_strts, labels = ~street_name, values = ~n, type = 'pie',
                     textinfo = 'none', marker = list(colors = color_palette)) %>%
  layout(title = "Distribution of Violent Crime Incidents for Top 10 Streets")

# Convert the pie chart to an interactive plotly object
pie_intrco4 <- ggplotly(pie_chrt_co4)

# Display the interactive pie chart
pie_intrco4

```

```{r}
# Create a bar plot with ggplot
p_barco4 <- ggplot(cleaned_crimeco4, aes(x = street_name, fill = category)) +
  geom_bar() +
  theme(axis.text.x = element_blank()) 

# Convert it to an interactive chart
p_barco4_intrctive <- ggplotly(p_barco4)

# Display the interactive chart
p_barco4_intrctive
```

```{r}

#use meaningful colours for bar plot
custm_pal <- c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00", "#FFFF33", "#A65628", "#F781BF",
                    "#999999", "#FFA500", "#DECF3F", "#0072B2", "#D55E00", "#CC79A7")

# Create the bar plot
bari_pltco4 <- ggplot(data = cleaned_crimeco4, aes(x = category, fill = outcome_status)) +
  geom_bar(position = "dodge") +
  labs(title = "Bar Plot of Category and Outcome Status",
       x = "Category",
       y = "Count",
       fill = "Outcome Status") +
  scale_x_discrete(labels = NULL) + 
  scale_fill_manual(values = custm_pal) +  
  theme_minimal() +
  guides(fill = "none") +  
  theme(panel.background = element_rect(fill = "lightgray"))  

# Convert to plotly object
bari_plt4_intcve <- ggplotly(bari_pltco4)

# Display the interactive plot
bari_plt4_intcve

```
```{r}

# Create the 2D density plot
den_pltco4 <- ggplot(vc_co4, aes(x = date, y = lat)) +
  geom_density_2d(alpha = 0.5) +  
  labs(title = "2D Density Plot of Violent Crimes",
       x = "Date",
       y = "Latitude") +
  theme_minimal() +
  theme(panel.background = element_rect(fill = "grey90")) 

# Convert ggplot object to plotly object
den_pltco4_intr <- ggplotly(den_pltco4)

# Display the interactive plot
den_pltco4_intr
```



```{r}

# Create a ggplot object for the box plot
g_boxco4 <- ggplot(cleaned_crimeco4, aes(x = factor(category), y = outcome_status))

# Add the box plot layer
g_boxco4 <- g_boxco4+ geom_boxplot(fill = "lightblue", color = "blue") 

# Set labels and title
g_boxco4 <- g_boxco4+ labs(title = "Outcome Status of Incidents by Category",
              x = "Incident Category")

# Customize the plot appearance by rotating and aligning thr labels
g_boxco4 <- g_boxco4+ theme_minimal() +
       theme(axis.text.x = element_text(angle = 45, hjust = 1),  
             axis.text.y = element_blank(),  # Remove y-axis labels
             panel.background = element_rect(fill = "grey90"))  

# Convert ggplot object to plotly object
g_boxco4_in <- ggplotly(g_boxco4)

# Display the interactive plot
g_boxco4_in

```


```{r}

# Convert date column to Date format using lubridate's ymd() function
cleaned_crimeco4$date <- ymd(cleaned_crimeco4$date)

# Group by date and category, count occurrences
dc_cs <- cleaned_crimeco4 %>%
  group_by(date, category) %>%
  summarise(count = n(), .groups = "drop")

# Get the number of unique categories
num_caty <- length(unique(dc_cs$category))

# Create a custom color palette
cus_pl <- viridis(num_caty)

# Create the interactive time series plot using plotly
pltyy <- plot_ly(dc_cs, x = ~date, y = ~count, color = ~category, type = 'scatter', mode = 'lines', name = ~category, colors = cus_pl) %>%
  layout(title = "Daily Crime Counts by Category",
         xaxis = list(title = "Date"),
         yaxis = list(title = "Count"))

# Display the interactive plot
pltyy
```

```{r}

# Convert date column to Date format using lubridate's ymd() function
vc_co4$date <- ymd(vc_co4$date)

# Group by date, count occurrences
dly_vcco4_cs <- vc_co4 %>%
  group_by(date) %>%
  summarise(count = n(), .groups = "drop") %>%
  ungroup()

# Create a smoothed time series using loess smoothing
smd_cont <- loess(count ~ as.numeric(date), data = dly_vcco4_cs)

# Create the interactive time series plot using plotly
plt_ty <- plot_ly(dly_vcco4_cs, x = ~date, y = ~count, type = 'scatter', mode = 'lines', name = 'Daily Counts') %>%
  add_trace(x = dly_vcco4_cs$date, y = predict(smd_cont), mode = 'lines', name = 'Smoothed') %>%
  layout(title = "Daily Violent Crime Counts with Smoothing",
         xaxis = list(title = "Date"),
         yaxis = list(title = "Count"))

# Display the interactive plot
plt_ty


```




```{r}
# Convert Date column to character format
cleaned_tempco4$Date <- as.character(cleaned_tempco4$Date)

cleaned_tempco4$Date <- ymd(cleaned_tempco4$Date)

# Group crime data by date and count occurrences
dc_count <- cleaned_crimeco4 %>%
  group_by(date) %>%
  summarise(count = n(), .groups = "drop")

# Merge crime counts with temperature data
mrge_dt <- left_join(dc_count, cleaned_tempco4, by = c("date" = "Date"))

# Create time series plot with crime counts and temperature
tm_plt <- plot_ly(mrge_dt, x = ~date) %>%
  add_trace(y = ~count, mode = "lines", name = "Crime Counts", type = 'scatter', line = list(color = 'red')) %>%
  add_trace(y = ~TemperatureCAvg, mode = "lines", name = "Average Temperature", type = 'scatter', line = list(color = 'blue')) %>%
  layout(title = "Crime Counts and Temperature Over Time",
         xaxis = list(title = "Date"),
         yaxis = list(title = "Count/Temperature"),
         plot_bgcolor = "rgba(211,211,211,0.2)",  
         paper_bgcolor = "rgba(211,211,211,0.2)")  

tm_plt



```

```{r}

#Convert date column to Date format
vc_co4$date <- ymd(vc_co4$date)

# Group by date and calculate minimum and maximum temperatures
c_wtr_dta <- vc_co4 %>%
  left_join(cleaned_tempco4, by = c("date" = "Date")) %>%
  group_by(date) %>%
  summarise(min_temp = min(TemperatureCMin, na.rm = TRUE),
            max_temp = max(TemperatureCMax, na.rm = TRUE))

# Create scatter plot
scattr_pltco4 <- plot_ly(data = c_wtr_dta, x = ~date) %>%
  add_trace(y = ~min_temp, name = "Minimum Temperature", type = 'scatter', mode = 'markers', marker = list(color = 'blue')) %>%
  add_trace(y = ~max_temp, name = "Maximum Temperature", type = 'scatter', mode = 'markers', marker = list(color = 'red')) %>%
  layout(title = "Minimum and Maximum Temperature During Violent Crimes",
         xaxis = list(title = "Date"),
         yaxis = list(title = "Temperature (°C)", side = "left"),
         yaxis2 = list(title = "", overlaying = "y", side = "right"),
         legend = list(x = 1.05, y = 1, bgcolor = "rgba(255, 255, 255, 0.5)"),  
         margin = list(r = 150),  
         plot_bgcolor = "rgba(211,211,211,0.2)",  
         paper_bgcolor = "rgba(211,211,211,0.2)")  

# Make the plot interactive
scattr_pltco4 <- scattr_pltco4 %>% config(displayModeBar = TRUE)

# Display the interactive plot
scattr_pltco4


```

```{r}

# Select  weather variables from cleaned_tempco4
wthr_dta <- cleaned_tempco4[, c("Date", "TemperatureCAvg", "Precmm", "SunD1h")]

# Calculate count of crime incidents for each date from cleaned_crimeco4
crm_counnt <- cleaned_crimeco4 %>%
  group_by(date) %>%
  summarise(crm_counnt = n())

# Merge crime incident count and weather data based on the date
merge_datz <- left_join(crm_counnt, wthr_dta, by = c("date" = "Date"))

#Calculate correlation coefficients
cor_mat <- cor(merge_datz[, -1], use = "complete.obs")

#Visualize the correlation coefficients
hetymay_plt <- plot_ly(z = cor_mat, type = "heatmap", colorscale = "Viridis") %>%
  layout(title = "Correlation Between Crime Incidents and Weather Variables",
         xaxis = list(title = "Weather Variables"),
         yaxis = list(title = "Weather Variables"),
         margin = list(l = 100, b = 100))  # Adjust margins for better display

# Display the interactive heatmap
hetymay_plt 
```

```{r}

# Step 1: Prepare the data
# Filter crime data to include only violent crime incidents
#violent_crime_data <- cleaned_crimeco4 %>%
  #filter(category == "violent-crime")

# Calculate count of violent crime incidents for each date
vt_cri_cnt <- vc_co4 %>%
  group_by(date) %>%
  summarise(vt_cri_cnt = n())

# Select relevant weather variables from cleaned_tempco4
weather_data <- cleaned_tempco4[, c("Date", "TemperatureCAvg", "Precmm", "SunD1h")]

# Merge violent crime incident count and weather data based on the date
merg_dta2 <- left_join(vt_cri_cnt, wthr_dta, by = c("date" = "Date"))

# Calculate correlation coefficients
cor_max2 <- cor(merg_dta2[, -1], use = "complete.obs")

# Visualize the correlation coefficients
hp_vc <- plot_ly(z = cor_max2, type = "heatmap", colorscale = "Portland") %>%
  layout(title = "Correlation Between Violent Crime Incidents and Weather Variables",
         xaxis = list(title = "Weather Variables"),
         yaxis = list(title = "Weather Variables"),
         margin = list(l = 100, b = 100)) 


hp_vc
```

```{r}
# Merge crime counts with weather data
meda_co4 <- left_join(crm_counnt, cleaned_tempco4, by = c("date" = "Date"))

# Create line plots for each weather variable
tempco4_plt <- plot_ly(meda_co4, x = ~date) %>%
  add_trace(y = ~TemperatureCAvg, name = "Average Temperature", type = 'scatter', mode = 'lines', line = list(color = 'blue')) %>%
  layout(title = "Average Temperature Over Time",
         xaxis = list(title = "Date"),
         yaxis = list(title = "Average Temperature (°C)"))

precico4_plot <- plot_ly(meda_co4, x = ~date) %>%
  add_trace(y = ~Precmm, name = "Precipitation", type = 'scatter', mode = 'lines', line = list(color = 'green')) %>%
  layout(title = "Precipitation Over Time",
         xaxis = list(title = "Date"),
         yaxis = list(title = "Precipitation (mm)"))

sunlight_plt <- plot_ly(meda_co4, x = ~date) %>%
  add_trace(y = ~SunD1h, name = "Sunlight Hours", type = 'scatter', mode = 'lines', line = list(color = 'orange')) %>%
  layout(title = "Sunlight Hours Over Time",
         xaxis = list(title = "Date"),
         yaxis = list(title = "Sunlight Hours"))

# Combine plots into a single subplot
subbyplt <- subplot(tempco4_plt, precico4_plot, sunlight_plt, nrows = 3)

# Make the subplot interactive
subplot <- subplot %>% config(displayModeBar = TRUE)

# Display the subplot
subbyplt

```

```{r}

# Filtered crime data with latitude and longitude columns
cr_dtsm <- cleaned_crimeco4 %>%
  filter(!is.na(lat) & !is.na(long))

# Calculate the 2D kernel density estimation of crime incidents
den_we <- kde2d(cr_dtsm$long, cr_dtsm$lat)


# Create a point density plot (heatmap)
den_we_plt <- plot_ly(z = ~den_we$z, type = "heatmap", colorscale = "Viridis", zauto = FALSE, zmax = max(density$z)) %>%
  layout(title = "Point Density Plot of Crime Incidents",
         xaxis = list(title = "Longitude"),
         yaxis = list(title = "Latitude"))

# Display the interactive point density plot
den_we_plt
```



```{r}

# Function to categorize dates into seasons
get_sew <- function(date) {
  month <- month(date)
  if (month %in% 3:5) {
    return("Spring")
  } else if (month %in% 6:8) {
    return("Summer")
  } else if (month %in% 9:11) {
    return("Fall")
  } else {
    return("Winter")
  }
}

# Apply the function to categorize dates into seasons
vc_co4 <- vc_co4 %>%
  mutate(season = factor(sapply(date, get_sew)))

# Aggregate violent crime incidents by season
vc_seson <- violent_crimes %>%
  group_by(season) %>%
  summarise(violent_crime_count = n())

# Create interactive bar plot for violent crime incidents by season
vil_plt <- plot_ly(data = vc_seson, x = ~season, y = ~violent_crime_count, type = "bar") %>%
  layout(title = "Violent Crime Incidents by Season",
         xaxis = list(title = "Season"),
         yaxis = list(title = "Violent Crime Count"))

# Display the interactive plot
vil_plt


```



```{r}
# Define the path to the downloaded icon
icon_path <- "/Users/nithyashree/Downloads/icons8-location-48-2.png"

# Define a custom icon with popup
customIcon <- makeIcon(
  iconUrl = icon_path,  
  iconWidth = 19,       
  iconHeight = 19      
)

# Create Leaflet map
crime_map <- leaflet() %>%
  addTiles() %>%
  addMarkers(
    data = cleaned_crimeco4,
    lng = ~long,
    lat = ~lat,
    icon = customIcon,  
    label = ~paste("Category: ", category, "<br>Date: ", date),
    labelOptions = labelOptions(noHide = TRUE)  # Prevent the label from hiding on mouseout
  )

# Display the map
crime_map

```

```{r}


library(leaflet)

# Define the path to the downloaded icon
icon_path <- "/Users/nithyashree/Downloads/icons8-danger-48-2.png"

# Define a custom icon with popup
customIcon <- makeIcon(
  iconUrl = icon_path,  # Local file path to the icon
  iconWidth = 12,       # Icon width
  iconHeight = 12       # Icon height
)

# Filter the dataset to include only violent crime incidents
violent_crimes <- cleaned_crimeco4 %>%
  filter(category == "violent-crime")

# Create Leaflet map for violent crimes
violent_crime_map <- leaflet() %>%
  addTiles() %>%
  addMarkers(
    data = violent_crimes,
    lng = ~long,
    lat = ~lat,
    icon = customIcon,  # Use custom icon
    popup = ~paste("Category: ", category, "<br>Date: ", date)  # Specify popup content
  )

# Display the map
violent_crime_map


```

